In [13]:
import numpy as np
a = np.array([[1,4,6],[3,1,5]])

In [14]:
a

array([[1, 4, 6],
       [3, 1, 5]])

In [15]:
np.sort(a)

array([[1, 4, 6],
       [1, 3, 5]])

In [16]:
np.sort(a, axis=0)

array([[1, 1, 5],
       [3, 4, 6]])

In [17]:
3*np.sqrt(3)

5.196152422706632