In [1]:
from multipole import operation as op
import numpy as np

In [2]:
x = np.array([0.12, 0.13, 0.115])
p = 5

In [3]:
y1 = np.array([0.125, 0.125, 0.125])
r_y1 = op.cartesian_to_spherical(x - y1)
Olm_y1 = op.O_expansion(p, r_y1)

In [4]:
Olm_y1.Vp

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-8.66025404e-03+0.00000000e+00j,  3.53553391e-03+2.50000000e-03j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 1.87500000e-05+0.00000000e+00j, -3.06186218e-05-2.16506351e-05j,
         3.12500000e-06+8.83883476e-06j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 5.41265877e-08+0.00000000e+00j,  9.94368911e-08+7.03125000e-08j,
        -2.70632939e-08-7.65465545e-08j, -3.68284782e-09+1.30208333e-08j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-3.80859375e-10+0.00000000e+00j, -9.56831931e-11-6.76582347e-11j,
         9.76562500e-11+2.76213586

In [5]:
y1 = np.array([0.125, 0.125, 0.125])
r_y1_op = op.cartesian_to_spherical(y1-x)
Olm_y1_op = op.O_expansion(p, r_y1_op)


In [6]:
Olm_y1_op.Vp

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 8.66025404e-03+0.00000000e+00j, -3.53553391e-03+2.50000000e-03j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 1.87500000e-05+0.00000000e+00j, -3.06186218e-05+2.16506351e-05j,
         3.12500000e-06-8.83883476e-06j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-5.41265877e-08+0.00000000e+00j, -9.94368911e-08+7.03125000e-08j,
         2.70632939e-08-7.65465545e-08j,  3.68284782e-09+1.30208333e-08j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-3.80859375e-10+0.00000000e+00j, -9.56831931e-11+6.76582347e-11j,
         9.76562500e-11-2.76213586

O or M expansion on vectors with oppsite direction only vary on sign of (-1)^l

In [7]:
y2 = np.array([0.25, 0.25, 0.25])
r_y2 = op.cartesian_to_spherical(x-y2)
Olm_y2 = op.O_expansion(p, r_y2)

In [8]:
Olm_y2.Vp

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-1.63524724e-01+0.00000000e+00j,  4.57839069e-02+6.00000000e-02j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 7.67400160e-03+0.00000000e+00j, -7.48680076e-03-9.81148346e-03j,
        -7.51916933e-04+2.74703442e-03j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 2.02679666e-04+0.00000000e+00j,  4.81742145e-04+6.31325080e-04j,
         1.22957009e-04-4.49208046e-04j, -6.64159199e-05+2.68849840e-05j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-3.82535553e-05+0.00000000e+00j, -1.20435635e-05-1.57831399e-05j,
        -8.62557426e-06+3.15124561

In [13]:
Y12 = y1 - y2
Olm_y2_t = op.O_to_O(Olm_y1, Y12)

In [14]:
Olm_y2_t.Vp

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-1.61753363e-01+0.00000000e+00j,  4.77297077e-02+6.50000000e-02j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 6.57895021e-03+0.00000000e+00j, -7.72044074e-03-1.05139686e-02j,
        -9.73437500e-04+3.10243100e-03j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 3.46545785e-04+0.00000000e+00j,  4.69207499e-04+6.38983326e-04j,
         1.57456789e-04-5.01828648e-04j, -8.27066342e-05+2.82682292e-05j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [-4.59782630e-05+0.00000000e+00j, -8.56296656e-06-1.16613500e-05j,
        -1.06244540e-05+3.38610702

In [ ]:
y3 = np.array([0.75, 0.75, 0.75])
r_y3 = op.cartesian_to_spherical(x-y3)
Mlm_y3 = op.M_expansion(p, r_y3)

In [ ]:
Mlm_y3.Vp

In [ ]:
Y13 = y3 - y1
Mlm_y3_t = op.O_to_M(Olm_y1, Y13)

In [ ]:
Mlm_y3_t.Vp

In [ ]:
y4 = np.array([0.875, 0.875, 0.875])
r_y4 = op.cartesian_to_spherical(x-y4)
Mlm_y4 = op.M_expansion(p, r_y4)

In [ ]:
Mlm_y4.Vp

In [ ]:
Y34 = y4 - y3
Mlm_y4_t = op.M_to_M(Mlm_y3, Y34)

In [ ]:
Mlm_y4_t.Vp

In [ ]:
x = np.array([0.1, 0.1, 0.1])
op.cartesian_to_spherical(x)

In [ ]:
x = [0.1, 0.1, 0.1]
op.cartesian_to_spherical(x)

In [ ]:
r_power = np.power(r[])