In [1]:
from multipole import operation as op

In [2]:
p = 3
z = 0.01224745
[P1lm, P2lm] = op.polynoimal_generation(p, z)

In [3]:
P1lm.Vn

array([[ 0.49996250+0.j,  0.00000000+0.j,  0.00000000+0.j],
       [ 0.00612327+0.j,  0.12498125+0.j,  0.00000000+0.j],
       [-0.06244844+0.j,  0.00153070+0.j,  0.02082865+0.j]])

In [4]:
P1lm.Vp

array([[ 1.00000000+0.j,  0.00000000+0.j,  0.00000000+0.j,  0.00000000+0.j],
       [ 0.01224745+0.j, -0.49996250+0.j,  0.00000000+0.j,  0.00000000+0.j],
       [-0.24988750+0.j, -0.00612327+0.j,  0.12498125+0.j,  0.00000000+0.j],
       [-0.00306110+0.j,  0.06244844+0.j,  0.00153070+0.j, -0.02082865+0.j]])

In [4]:
P2lm.Vp

array([[ 1.00000000+0.j,  0.00000000+0.j,  0.00000000+0.j,  0.00000000+0.j],
       [ 0.50000000+0.j, -0.86602540+0.j,  0.00000000+0.j,  0.00000000+0.j],
       [-0.25000000+0.j, -1.29903811+0.j,  2.25000000+0.j,  0.00000000+0.j],
       [-2.62500000+0.j, -0.64951905+0.j,  5.62500000+0.j, -9.74278579+0.j]])

In [5]:
import numpy as np
from scipy.special import factorial as fc
from scipy.special import factorial2 as fc2


In [6]:
def Pmm(m, x):
    return np.power(-1, m) * fc2(2*m-1) * np.power((1 - x*x), m/2) / fc(2*m)

In [65]:
-1 * Pmm(1, 0.01224745)

0.4999624985857683

In [68]:
P1lm.Vn[0,0]

(0.4999624985857683+0j)

In [8]:
(0.5*3*0.5 - 1)/4

-0.0625

In [9]:
def Plm(P1, P2, x, l, m):
    return (x * (2*l-1) * P1 - P2) / ((l+m) * (l-m))

In [10]:
Plm(-0.21650635, -0.4330127, 0.5, 3, 1)

-0.013531646875000004

In [36]:
type(np.power(0.3, 2)*Pmm(1, 0.5)*np.exp(-2*0.4*1j))

numpy.complex128

In [22]:
np.exp(-2*0.4*1j)

(0.6967067093471655-0.71735609089952279j)

In [25]:
from scipy.special import factorial

In [38]:
type(op.cartesian_to_spherical([0.25, 0.25, 0.25])[1])

numpy.float64

In [50]:
op.cartesian_to_spherical([0.25, 0.25, 0.25])[2]

0.95531661812450919

In [51]:
op.cartesian_to_spherical(np.array([0.25, 0.25, 0.25]))[2]

0.95531661812450919