In [2]:
import numpy as np
from scipy.special import lpmn, factorial
from multipole import Vlm

In [3]:
import numpy as np

def spherical_to_cartesian(r):
    x=np.ndarray(shape=(len(r), 3))
    for i in range(0, len(r)):
        x[i][0] = r[i][0] * np.cos(r[i][1]) * np.sin(r[i][2])
        x[i][1] = r[i][0] * np.sin(r[i][1]) * np.sin(r[i][2])
        x[i][2] = r[i][0] * np.cos(r[i][2])
    return x

def cartesian_to_spherical(x):
    r=np.ndarray(shape=(len(x), 3))
    for i in range(0, len(x)):
        r[i][0] = np.sqrt(sum( x[i] * x[i] ))
        r[i][1] = np.arctan2(x[i][1], x[i][0])
        r[i][2] = np.arccos(x[i][2] / r[i][0])
    return r

def distance_cal(x1, x2):
    return np.sqrt(sum( (x1-x2) * (x1-x2) ))

In [4]:
# STEP 1
r1 = [2, 0.3*np.pi, 0.25*np.pi]
r2 = [15, -0.3*np.pi, -0.3*np.pi]
r = [r1, r2]
x = spherical_to_cartesian(r)

In [5]:
p = 2
[P0lm, _] = lpmn(p, p, 0.1)

In [6]:
Plm = Vlm(p)
Plm.Vp = P0lm

In [7]:
Plm.setlm(1, 2, 3)

Exception: Range Error

In [8]:
Plm.getlm(3, 2)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [9]:
np.dtype(Plm.Vn[1][2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [10]:
p2 = Plm.add(Plm)

In [11]:
Plm.Vp

array([[ 2.        ,  0.2       , -0.97      ],
       [ 0.        , -1.98997487, -0.59699246],
       [ 0.        ,  0.        ,  5.94      ]])

In [12]:
p2.Vn

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])

In [13]:
p2.Vp * p2.Vp

array([[  4.    ,   0.04  ,   0.9409],
       [  0.    ,   3.96  ,   0.3564],
       [  0.    ,   0.    ,  35.2836]])

In [14]:
sum(sum(Plm.Vp))

4.583032663522788