In [1]:
import numpy as np
from scipy.special import lpmn, factorial

In [2]:
import numpy as np

def spherical_to_cartesian(r):
    x=np.ndarray(shape=(len(r), 3))
    for i in range(0, len(r)):
        x[i][0] = r[i][0] * np.cos(r[i][1]) * np.sin(r[i][2])
        x[i][1] = r[i][0] * np.sin(r[i][1]) * np.sin(r[i][2])
        x[i][2] = r[i][0] * np.cos(r[i][2])
    return x

def cartesian_to_spherical(x):
    r=np.ndarray(shape=(len(x), 3))
    for i in range(0, len(x)):
        r[i][0] = np.sqrt(sum( x[i] * x[i]))
        r[i][1] = np.arctan( x[i][1] / x[i][0])
        r[i][2] = np.arctan( np.sqrt(x[i][0]*x[i][0] + x[i][1]*x[i][1]) / x[i][2] )
    return r

def distance_cal(x1, x2):
    return np.sqrt(sum( (x1-x2) * (x1-x2) ))

In [75]:
# STEP 1
r1 = [2, 0.3*np.pi, 0.25*np.pi]
r2 = [15, -0.3*np.pi, -0.3*np.pi]
r = [r1, r2]
x = spherical_to_cartesian(r)

In [76]:
x

array([[ 0.83125388,  1.14412281,  1.41421356],
       [-7.13292387,  9.81762746,  8.81677878]])

In [77]:
1 / distance_cal(x[0], x[1])

0.0718967307406988

In [78]:
def polynoimal_generation(p, z):
    [P0lm, _] = lpmn(p, p, z)
    P1lm = np.ndarray(shape=P0lm.shape) 
    P2lm = np.ndarray(shape=P0lm.shape) 
    for l in range(0, P0lm.shape[1]):
        for m in range(0, P0lm.shape[0]):
            P1lm[l][m] = factorial(l-m) * P0lm[m][l]
            P2lm[l][m] = P0lm[m][l] / factorial(l+m)

    return [P1lm, P2lm]

def chargeless_multipole_moment(p, r): 
    [P1lm_r, _] = polynoimal_generation(p, np.cos(r[1]))
    Olm = np.ndarray(shape=P1lm_r.shape, dtype=np.complex128)
    for l in range(0, Olm.shape[0]):
        r_power = np.power(r[0], l)
        for m in range(0, l+1):
            Olm[l][m] = r_power * P1lm_r[l][m] * np.exp(-m*r[2]*1j)

    return Olm

def chargeless_taylor_expansion_coefficient(p, r):
    [_, P1lm_r] = polynoimal_generation(p, np.cos(r[1]))
    Mlm = np.ndarray(shape=P1lm_r.shape, dtype=np.complex128)
    for l in range(0, Mlm.shape[0]):
        r_power = 1 / np.power(r[0], l+1)
        for m in range(0, l+1):
            Mlm[l][m] = r_power * P1lm_r[l][m] * np.exp(m*r[2]*1j)

    return Mlm

In [80]:
p0 = 50
potential = 0

Mlm = chargeless_taylor_expansion_coefficient(p0, r[1])
Olm = chargeless_multipole_moment(p0, r[0])

for l in range (0, Mlm.shape[0]):
    potential += Olm[l][0] * Mlm[l][0]
    for m in range (1, l+1):
        potential += 2 * Olm[l][m] * Mlm[l][m]

potential.real

0.06828084521493875

In [100]:
#STEP 2
#Construction:
d = 1
X = np.ndarray(shape=(2,3))
X[0] = [3,1,4]
X[1] = [-4,-2,-3]
num_charge = 10
x0_i = np.ndarray(shape=(2*num_charge,3))

for i in range(0, num_charge):
    xi_dev = np.random.rand(3)
    x0_i[i] = X[0] + xi_dev
    xi_dev = np.random.rand(3)
    x0_i[i+num_charge] = X[1] + xi_dev


In [101]:
p = 5
s = p+1
OlmQ_X1 = np.zeros(shape=(s, s), dtype=np.complex128)
xa_k = x0_i[0:num_charge] - X[0]
ra_k = cartesian_to_spherical(xa_k)

for i in range(0, num_charge):
    OlmQ1_X1 += chargeless_multipole_moment(p, ra_k[i])

MlmQ1_X2 

NameError: name 'OlmQ1_X1' is not defined

In [ ]:
#construction conversion operator C
def conversion_operation(Ojk_x1_1, X12, p):
    Clmjk_X12 = chargeless_taylor_expansion_coefficient(p*2, X12)
    Mlm_x2_1 = np.ndarray(shape=Ojk_x1_1.shape, dtype=np.complex128)
    for l in range(0, Mlm_x2_1.shape[1]):
        for m in range(0, l+1):
            Mlm_x2_1 = 

In [86]:
xa_k

array([[0.40829444, 0.40645093, 0.20393395],
       [0.68376455, 0.96515441, 0.59845951],
       [0.73324664, 0.35693885, 0.12634662],
       [0.4421118 , 0.72578772, 0.42328666],
       [0.34681546, 0.34164562, 0.51604562],
       [0.00703333, 0.2119606 , 0.64564601],
       [0.74178821, 0.87015986, 0.70338321],
       [0.40230423, 0.98358706, 0.17746667],
       [0.34708503, 0.42951777, 0.26393482],
       [0.60673371, 0.98864167, 0.71755215]])

In [91]:
for x in range(0,1):
    print(x)

0


In [1]:
from multipole import operation as op

In [2]:
x = [1, 2, 3]

In [3]:
op.cartesian_to_spherical(x)

TypeError: 'int' object is not iterable

In [7]:
import numpy as np 
np.dtype(x)

TypeError: data type not understood

In [9]:
type(x) 

list

In [14]:
y = np.ndarray([2,2])

In [15]:
y

array([[2.31584178e+077, 2.31584178e+077],
       [4.46922374e-313, 2.21495150e-314]])

In [21]:
if type(y) == np.ndarray:
    print(x)

[1, 2, 3]


In [22]:
z = 

TypeError: 'int' object is not iterable