In [1]:
from multipole_test import operation as op
import numpy as np

In [45]:
p = 10
z = np.float128(0.01224745)
[P1lm, P2lm] = op.polynoimal_generation(p, z)

In [20]:
P1lm.Vp[5][5]

-0.00026031902138221534688

In [25]:
P1lm.getlm(1,1)

-0.4999624985857683

In [29]:
P1lm.Vp

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01224745, -0.4999625 ,  0.        ,  0.        ],
       [-0.2498875 , -0.00612327,  0.12498125,  0.        ],
       [-0.0030611 ,  0.06244844,  0.0015307 , -0.02082865]])

In [30]:
P2lm.Vp

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.22474500e-02, -9.99924997e-01,  0.00000000e+00,
         0.00000000e+00],
       [-9.99550000e-01, -3.67395942e-02,  2.99955000e+00,
         0.00000000e+00],
       [-1.10199493e-01,  2.99752516e+00,  1.83684193e-01,
        -1.49966251e+01]])

In [9]:
import numpy as np
from scipy.special import factorial as fc
from scipy.special import factorial2 as fc2


In [10]:
def Pmm(m, x):
    return fc2(2*m-1) * np.power((1 - x*x), m/2) / fc(2*m)

In [21]:
Pmm(5, np.float128(0.01224745))

0.0002603190213822153288

In [39]:
Pmm(1, np.float64(0.01224745))

0.49996249858576830016

In [12]:
np.float128(0.01224745)

0.012247450000000000003

In [68]:
P1lm.Vn[0,0]

(0.4999624985857683+0j)

In [8]:
(0.5*3*0.5 - 1)/4

-0.0625

In [9]:
def Plm(P1, P2, x, l, m):
    return (x * (2*l-1) * P1 - P2) / ((l+m) * (l-m))

In [10]:
Plm(-0.21650635, -0.4330127, 0.5, 3, 1)

-0.013531646875000004

In [36]:
type(np.power(0.3, 2)*Pmm(1, 0.5)*np.exp(-2*0.4*1j))

numpy.complex128

In [22]:
np.exp(-2*0.4*1j)

(0.6967067093471655-0.71735609089952279j)

In [25]:
from scipy.special import factorial

In [38]:
type(op.cartesian_to_spherical([0.25, 0.25, 0.25])[1])

numpy.float64

In [50]:
op.cartesian_to_spherical([0.25, 0.25, 0.25])[2]

0.95531661812450919

In [51]:
op.cartesian_to_spherical(np.array([0.25, 0.25, 0.25]))[2]

0.95531661812450919

In [23]:
import numpy as np
from scipy.special import factorial2 as fc2


def AL_polynoimal(p, x):
    if p < 0:
        raise Exception("Error: input level can not be nagative")
        
    P = np.zeros(shape=(p+1, p+1), dtype=np.float128)
    
    for l in range(0, p+1):
        P[l][l] = np.power(-1, l) * int(fc2(2*l-1)) * np.power(1-x*x, l/2)
    
    if p==0:
        return P
    elif p==1:
        P[1][0] = x
        return P
    
    for l in range(0, p+1):
        for m in range(0, l):
            P[l][m] = ((2*l-1) * x * P[l-1][m] - (l+m-1) * P[l-2][m]) / (l-m)
    
    return P

In [37]:
AL = AL_polynoimal(10, np.float128(0.01224745)) 
AL

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.22474500e-02, -9.99924997e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-4.99775000e-01, -3.67395942e-02,  2.99955000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.83665822e-02,  1.49876258e+00,  1.83684193e-01,
        -1.49966251e+01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 3.74437598e-01,  9.18168384e-02, -7.49100118e+00,
        -1.28569291e+00,  1.04968502e+02,  0.00000000e+00,
  

In [43]:
AL[10][10] ** 2 / fc(20)

0.17593293469669278287

In [65]:
from scipy.special import lpmn
[P0lm, _] = lpmn(10, 10, np.float128(0.01224745))

In [63]:
x1 = 0.012223
x2 = 0.963
p = 10 
[P1lm, _] = op.polynoimal_generation(p, x1)
[_, P2lm] = op.polynoimal_generation(p, x2)


sum(sum(P1lm.product(P2lm).Vp))

0.86505201083288251217

In [64]:
P2lm.Vp

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 9.63000000e-01, -2.69501391e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.78210700e+00, -7.78589520e-01,  2.17893000e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 4.72884520e+00, -2.94040436e+00,  1.04915480e+00,
        -2.93612333e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.58381825e+01, -1.35925497e+01,  5.98288747e+00,
        -1.97924074e+00,  5.53902527e-01,  0.00000000e+00,
  

In [39]:
P0lm.transpose() - AL

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.83230167e-17, -1.70423029e-18,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-5.37018889e-19, -9.75781955e-19, -1.27664806e-17,
         4.44089210e-16,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.14383329e-17,  1.25564164e-17, -2.84494650e-16,
         1.48535698e-17,  3.10862447e-15,  0.00000000e+00,
  