In [1]:
from multipole import operation as op
import numpy as np

In [2]:
x1 = np.array([0.12, 0.13, 0.115])
x2 = np.array([0.86, 0.76, 0.92])
y1 = np.array([0.125, 0.125, 0.125])
y2 = np.array([0.25, 0.25, 0.25])
y3 = np.array([0.75, 0.75, 0.75])
y4 = np.array([0.875, 0.875, 0.875])
p=5

In [3]:
1 / op.distance_cal(x1, x2)

0.79242263181687467

In [11]:
# interaction at lowest level:
r1_y1 = op.cartesian_to_spherical(x1 - y1)
r2_y4 = op.cartesian_to_spherical(x2 - y4)
Olm_1_y1 = op.O_expansion(p, r1_y1)
Olm_2_y4 = op.O_expansion(p, r2_y4)
Mlm_1_y4 = op.O_to_M(Olm_1_y1, y1-y4)
Olm_2_y4.product(Mlm_1_y4).sum()

(0.80278550789511849+0j)

In [13]:
Olm_1_y2 = op.O_to_O(Olm_1_y1, y1-y2)
Mlm_1_y3 = op.O_to_M(Olm_1_y2, y2-y3)
Mlm_1_y4 = op.M_to_M(Mlm_1_y3, y4-y3)

Olm_2_y4.product(Mlm_1_y4).sum()

(1.0187280027817471+2.0816681711721685e-17j)

In [14]:
r1_y3 = op.cartesian_to_spherical(x1 - y3)

op.M_expansion(p, r1_y3).Vp

array([[  0.91881459 +0.j        ,   0.00000000 +0.j        ,
          0.00000000 +0.j        ,   0.00000000 +0.j        ,
          0.00000000 +0.j        ,   0.00000000 +0.j        ],
       [ -0.60171025 +0.j        ,   0.34549372 -0.48092277j,
          0.00000000 +0.j        ,   0.00000000 +0.j        ,
          0.00000000 +0.j        ,   0.00000000 +0.j        ],
       [  0.40645612 +0.j        ,  -0.67876733 +0.94483532j,
         -0.36543000 -1.0850228j ,   0.00000000 +0.j        ,
          0.00000000 +0.j        ,   0.00000000 +0.j        ],
       [  0.70101075 +0.j        ,   1.34752608 -1.87573881j,
          1.19655790 +3.55278062j,  -3.52664154 -1.08359704j,
          0.00000000 +0.j        ,   0.00000000 +0.j        ],
       [ -6.30177553 +0.j        ,  -1.59301072 +2.21745025j,
         -3.94266798-11.70644094j,  16.16660697 +4.967357j  ,
        -13.25285107+10.06913023j,   0.00000000 +0.j        ],
       [ 27.67305261 +0.j        ,  -7.67510212+10.68364256j,
   

In [15]:
r1_y2 = op.cartesian_to_spherical(x1 - y2)

op.O_expansion(p, r1_y2).Vp

array([[  1.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [ -1.63524724e-01 +0.00000000e+00j,
          4.57839069e-02 +6.00000000e-02j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  7.67400160e-03 +0.00000000e+00j,
         -7.48680076e-03 -9.81148346e-03j,
         -7.51916933e-04 +2.74703442e-03j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  2.02679666e-04 +0.00000000e+00j,
          4.81742145e-04 +6.31325080e-04j,
          1.22957009e-04 -4.49208046e-04j,
         -6.64159199e-05 +2.68849840e-05j,
          0.00000000e+00 +0.00000000e+00j,
        

In [16]:
Olm_1_y2.Vp

array([[  1.00000000e+00 -0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  1.44432855e-01 +0.00000000e+00j,
         -4.06586399e-02 +6.50000000e-02j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  4.55229979e-03 -0.00000000e+00j,
         -5.87244344e-03 +9.38813557e-03j,
         -1.28593750e-03 -2.64281159e-03j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [ -3.46829032e-04 +0.00000000e+00j,
         -3.04588602e-04 +4.86938549e-04j,
         -1.85731624e-04 -3.81708824e-04j,
          7.46890745e-05 +7.95572917e-06j,
          0.00000000e+00 +0.00000000e+00j,
        

In [17]:
Mlm_1_y3.Vp

array([[   1.15470054 +0.00000000e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [  -0.96833189 +0.00000000e+00j,    0.55587806 -4.08928115e-01j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [   1.06126713 +0.00000000e+00j,   -1.26249308 +9.65075686e-01j,
           0.23622101 -1.10937338e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [  -0.31634766 -1.24900090e-16j,    3.57192662 -3.08881986e+00j,
          -0.47174712 +5.28930674e+00j,   -2.66991180 -3.13655559e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [  -7.98885149 +1.13797860e-15j,  -10.40023239 +9.61007374e+00j,
           3.26807633 -2.53353867e+01j,   13.37976047 +2.207

In [18]:
Mlm_1_y4.Vp

array([[   1.01079146 +1.21981215e-17j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [  -0.79410535 -1.14112279e-17j,    0.45625546 -1.87901510e-01j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [   0.93167087 +5.37764278e-17j,   -0.98253055 +3.96103732e-01j,
           0.50446204 -4.55456234e-01j,    0.00000000 +0.00000000e+00j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [  -0.67535873 +6.66133815e-16j,    2.42273135 -9.69274833e-01j,
          -1.09565076 +1.79761829e+00j,   -0.38590828 -6.69520845e-01j,
           0.00000000 +0.00000000e+00j,    0.00000000 +0.00000000e+00j],
       [   2.51973263 +3.55271368e-15j,  -10.90410799 +4.50027174e+00j,
          13.46523982 -5.77462045e+00j,  -14.53507869 +1.052

In [12]:
Mlm_1_y4.Vp

array([[  0.76980036 +0.00000000e+00j,   0.00000000 +0.00000000e+00j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j],
       [ -0.41705093 +0.00000000e+00j,   0.24172924 -3.35014105e-01j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j],
       [  0.23117020 -1.69406589e-21j,  -0.39464576 +5.47097378e-01j,
         -0.21085261 -6.34176859e-01j,   0.00000000 +0.00000000e+00j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j],
       [  0.35003504 +2.11758237e-22j,   0.64837376 -8.98841624e-01j,
          0.57381461 +1.72586768e+00j,  -1.71927061 -5.39237814e-01j,
          0.00000000 +0.00000000e+00j,   0.00000000 +0.00000000e+00j],
       [ -2.55491892 +7.45355906e-20j,  -0.61701183 +8.55364400e-01j,
         -1.56736708 -4.71418641e+00j,   6.55038838 +2.05448633e+00j,
         -5.4472