In [1]:
from fast_multipole_method import operation as op
import numpy as np

In [2]:
x1 = [0.13, 0.17, 0.14]
r1 = op.cartesian_to_spherical(x1)
r1

array([0.25573424, 0.9179497 , 0.9914903 ])

In [3]:
op.spherical_to_cartesian(r1)

array([0.13, 0.17, 0.14])

In [4]:
x2 = np.array([0.87, 0.83, 0.92])
op.distance_cal(x1, x2)

1.2615863030328127

In [5]:
r2 = op.cartesian_to_spherical(x2)
r2

array([1.51400132, 0.76187309, 0.91768381])

In [14]:
P1 = op.AL_polynoimal(2, np.float(np.cos(r1[1])))
P1

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.60745011, -0.79435783,  0.        ],
       [ 0.05349345, -1.44759825,  1.8930131 ]], dtype=float128)

In [15]:
P1

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.60745011, -0.79435783,  0.        ],
       [ 0.05349345, -1.44759825,  1.8930131 ]], dtype=float128)

In [8]:
np.cos(r1[1])

0.6074501075707971