In [1]:
from fast_multipole_method import operation as op
import numpy as np

In [41]:
x = np.array([0.12, 0.13, 0.115])
p = 2

In [42]:
y1 = np.array([0.125, 0.125, 0.125])
r_y1_op = op.cartesian_to_spherical(y1-x)
Mlm_y1_op = op.M_expansion(p, r_y1_op)

r_y1 = op.cartesian_to_spherical(x - y1)
Mlm_y1 = op.M_expansion(p, r_y1)

In [43]:
Mlm_y1_op.V_matrix

array([[  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          1.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
         -2.50000000e-03 +2.50000000e-03j,
          1.00000000e-02 +0.00000000e+00j,
         -2.50000000e-03 -2.50000000e-03j,
          0.00000000e+00 +0.00000000e+00j],
       [  3.82702125e-22 -6.25000000e-06j,
         -2.50000000e-05 +2.50000000e-05j,
          3.75000000e-05 +0.00000000e+00j,
         -2.50000000e-05 -2.50000000e-05j,
          3.82702125e-22 +6.25000000e-06j]])

In [44]:
Mlm_y1.V_matrix

array([[  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          1.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
          2.50000000e-03 -2.50000000e-03j,
         -1.00000000e-02 +0.00000000e+00j,
          2.50000000e-03 +2.50000000e-03j,
          0.00000000e+00 +0.00000000e+00j],
       [ -1.14810637e-21 -6.25000000e-06j,
         -2.50000000e-05 +2.50000000e-05j,
          3.75000000e-05 +0.00000000e+00j,
         -2.50000000e-05 -2.50000000e-05j,
         -1.14810637e-21 +6.25000000e-06j]])

    O expansion on vectors with the oppsite direction are different by:
    if l is odd, flip the sign of real part
    if l is even, flip the sign of image part

In [45]:
y2 = np.array([0.25, 0.25, 0.25])
r_y2 = op.cartesian_to_spherical(x-y2)
Mlm_y2 = op.M_expansion(p, r_y2)

In [46]:
y2 = np.array([0.25, 0.25, 0.25])
r_y2 = op.cartesian_to_spherical(x-y2)
Mlm_y2 = op.M_expansion(p, r_y2)
y21 = y1 - y2
y12 = y2 - y1
Mlm_y1_t = op.M2M(Mlm_y2, y12)

In [47]:
Mlm_y1_t.V_matrix

array([[  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          1.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
          2.50000000e-03 -2.50000000e-03j,
         -1.00000000e-02 +0.00000000e+00j,
          2.50000000e-03 +2.50000000e-03j,
          0.00000000e+00 +0.00000000e+00j],
       [ -1.08420217e-19 -6.25000000e-06j,
         -2.50000000e-05 +2.50000000e-05j,
          3.75000000e-05 +0.00000000e+00j,
         -2.50000000e-05 -2.50000000e-05j,
         -8.60718238e-20 +6.25000000e-06j]])

In [48]:
Mlm_y1.V_matrix

array([[  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          1.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
          2.50000000e-03 -2.50000000e-03j,
         -1.00000000e-02 +0.00000000e+00j,
          2.50000000e-03 +2.50000000e-03j,
          0.00000000e+00 +0.00000000e+00j],
       [ -1.14810637e-21 -6.25000000e-06j,
         -2.50000000e-05 +2.50000000e-05j,
          3.75000000e-05 +0.00000000e+00j,
         -2.50000000e-05 -2.50000000e-05j,
         -1.14810637e-21 +6.25000000e-06j]])

In [49]:
y3 = np.array([0.75, 0.75, 0.75])
r_y3 = op.cartesian_to_spherical(x-y3)
Llm_y3 = op.L_expansion(p, r_y3)

In [50]:
Y31 = y1 - y3
Llm_y3_t = op.M2L(Mlm_y1, Y31)

In [51]:
Llm_y3_t.V_matrix

array([[ 0.00000000 +0.00000000e+00j,  0.00000000 +0.00000000e+00j,
         0.91881400 -3.62009681e-21j,  0.00000000 +0.00000000e+00j,
         0.00000000 +0.00000000e+00j],
       [ 0.00000000 +0.00000000e+00j,  0.48867830 -4.80921669e-01j,
        -0.49255662 +9.65359151e-21j,  0.48867830 +4.80921669e-01j,
         0.00000000 +0.00000000e+00j],
       [ 0.02455216 -1.53468915e+00j, -0.78591004 +7.73432163e-01j,
         0.01646900 -2.05943285e-20j, -0.78591004 -7.73432163e-01j,
         0.02455216 +1.53468915e+00j]])

In [52]:
Llm_y3.V_matrix

array([[ 0.00000000+0.j        ,  0.00000000+0.j        ,
         0.91881459+0.j        ,  0.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        ,  0.48867959-0.48092277j,
        -0.49255800+0.j        ,  0.48867959+0.48092277j,  0.00000000+0.j        ],
       [ 0.02455674-1.53469794j, -0.78591387+0.77343904j,
         0.01646939+0.j        , -0.78591387-0.77343904j,
         0.02455674+1.53469794j]])

In [33]:
y4 = np.array([0.875, 0.875, 0.875])
r_y4 = op.cartesian_to_spherical(x-y4)
Llm_y4 = op.L_expansion(p, r_y4)

In [34]:
Y43 = y3 - y4
Llm_y4_t = op.L2L(Llm_y3, Y43)

In [35]:
Llm_y4_t.V_matrix

array([[  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          7.66320459e-01 +1.99052743e-20j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          3.40572600e-01 -3.36031548e-01j,
         -3.42843126e-01 +4.23516474e-20j,
          3.40572600e-01 +3.36031548e-01j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
         

In [16]:
Llm_y4_t.V_matrix

array([[ 0.00000000+0.j       ,  0.73604455+0.j       ,  0.00000000+0.j       ],
       [ 0.29401628-0.2908884j, -0.29558021+0.j       ,
         0.29401628+0.2908884j]])

In [36]:
Llm_y4.V_matrix

array([[  0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   7.66367905e-01 +0.j        ,
          0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ],
       [  0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          3.39827779e-01 -0.33532675j,  -3.42078294e-01 +0.j        ,
          3.39827779e-01 +0.33532675j,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ],
       [  0.00000000e+00 +0.j        ,   0.00000000e+00 +0.j        ,
          0.00000000e+00 +0.j        ,   1.18959480e-02 -0.89215645j,
         -4.55059664e-01 +0.44903238j,   7.97028516e-03 +0.j        ,
         -

In [18]:
x = np.array([0.1, 0.1, 0.1])
op.cartesian_to_spherical(x)

array([ 0.17320508,  0.95531662,  0.78539816])

In [19]:
x = [0.1, 0.1, 0.1]
op.cartesian_to_spherical(x)

array([ 0.17320508,  0.95531662,  0.78539816])

In [20]:
r_power = np.power(r[])

SyntaxError: invalid syntax (<ipython-input-20-763464502a9d>, line 1)

In [ ]:
from scipy.special import lpmn, factorial, sph_harm

In [ ]:
sph_harm(                 )