In [1]:
from fast_multipole_method import operation as op
import numpy as np

In [2]:
x = np.array([0.12, 0.13, 0.115])
p = 1

In [3]:
y1 = np.array([0.125, 0.125, 0.125])
r_y1_op = op.cartesian_to_spherical(y1-x)
Mlm_y1_op = op.M_expansion(p, r_y1_op)

r_y1 = op.cartesian_to_spherical(x - y1)
Mlm_y1 = op.M_expansion(p, r_y1)

In [4]:
Mlm_y1_op.V_matrix

array([[ 0.    +0.    j,  1.    +0.    j,  0.    +0.    j],
       [-0.0025+0.0025j,  0.01  +0.    j, -0.0025-0.0025j]])

In [5]:
Mlm_y1.V_matrix

array([[ 0.    +0.    j,  1.    +0.    j,  0.    +0.    j],
       [ 0.0025-0.0025j, -0.01  +0.    j,  0.0025+0.0025j]])

    O expansion on vectors with the oppsite direction are different by:
    if l is odd, flip the sign of real part
    if l is even, flip the sign of image part

In [6]:
y2 = np.array([0.25, 0.25, 0.25])
r_y2 = op.cartesian_to_spherical(x-y2)
Mlm_y2 = op.M_expansion(p, r_y2)

In [7]:
y2 = np.array([0.25, 0.25, 0.25])
r_y2 = op.cartesian_to_spherical(x-y2)
Mlm_y2 = op.M_expansion(p, r_y2)
y21 = y1 - y2
y12 = y2 - y1
Mlm_y1_t = op.M2M(Mlm_y2, y12)

In [8]:
Mlm_y1_t.V_matrix

array([[ 0.    +0.    j,  1.    +0.    j,  0.    +0.    j],
       [ 0.0025-0.0025j, -0.01  +0.    j,  0.0025+0.0025j]])

In [9]:
Mlm_y1.V_matrix

array([[ 0.    +0.    j,  1.    +0.    j,  0.    +0.    j],
       [ 0.0025-0.0025j, -0.01  +0.    j,  0.0025+0.0025j]])

In [10]:
y3 = np.array([0.75, 0.75, 0.75])
r_y3 = op.cartesian_to_spherical(x-y3)
Llm_y3 = op.L_expansion(p, r_y3)

In [11]:
Y31 = y1 - y3
Llm_y3_t = op.M2L(Mlm_y1, Y31)

In [12]:
Llm_y3_t.V_matrix

array([[ 0.        +0.       j,  0.91883371+0.       j,
         0.        +0.       j],
       [ 0.48873085-0.4808481j, -0.49267223+0.       j,
         0.48873085+0.4808481j]])

In [13]:
Llm_y3.V_matrix

array([[ 0.        +0.        j,  0.91881459+0.        j,
         0.        +0.        j],
       [ 0.48867959-0.48092277j, -0.492558  +0.        j,
         0.48867959+0.48092277j]])

In [14]:
y4 = np.array([0.875, 0.875, 0.875])
r_y4 = op.cartesian_to_spherical(x-y4)
Llm_y4 = op.L_expansion(p, r_y4)

In [15]:
Y43 = y3 - y4
Llm_y4_t = op.L2L(Llm_y3, Y43)

NameError: name 'Tlm_X12' is not defined

In [ ]:
Llm_y4_t.V_matrix

In [ ]:
Llm_y4.V_matrix

In [ ]:
x = np.array([0.1, 0.1, 0.1])
op.cartesian_to_spherical(x)

In [ ]:
x = [0.1, 0.1, 0.1]
op.cartesian_to_spherical(x)

In [ ]:
r_power = np.power(r[])

In [ ]:
from scipy.special import lpmn, factorial, sph_harm

In [ ]:
sph_harm(                 )