In [ ]:
import numpy as np
from scipy.special import lpmn, factorial
from multipole import Vlm

In [ ]:
import numpy as np

def spherical_to_cartesian(r):
    x=np.ndarray(shape=(len(r), 3))
    for i in range(0, len(r)):
        x[i][0] = r[i][0] * np.cos(r[i][1]) * np.sin(r[i][2])
        x[i][1] = r[i][0] * np.sin(r[i][1]) * np.sin(r[i][2])
        x[i][2] = r[i][0] * np.cos(r[i][2])
    return x

def cartesian_to_spherical(x):
    r=np.ndarray(shape=(len(x), 3))
    for i in range(0, len(x)):
        r[i][0] = np.sqrt(sum( x[i] * x[i] ))
        r[i][1] = np.arctan2(x[i][1], x[i][0])
        r[i][2] = np.arccos(x[i][2] / r[i][0])
    return r

def distance_cal(x1, x2):
    return np.sqrt(sum( (x1-x2) * (x1-x2) ))

In [ ]:
# STEP 1
r1 = [2, 0.3*np.pi, 0.25*np.pi]
r2 = [15, -0.3*np.pi, -0.3*np.pi]
r = [r1, r2]
x = spherical_to_cartesian(r)

In [ ]:
p = 2
[P0lm, _] = lpmn(p, p, 0.1)

In [ ]:
Plm = Vlm(p)
Plm.Vp = P0lm

In [ ]:
Plm.setlm(1, 2, 3)

In [ ]:
Plm.getlm(3, 2)

In [ ]:
np.dtype(Plm.Vn[1][2])

In [ ]:
p2 = Plm.add(Plm)

In [ ]:
Plm.Vp

In [ ]:
p2.Vn

In [ ]:
p2.Vp * p2.Vp

In [ ]:
sum(sum(Plm.Vp))

In [1]:
import numpy as np
d = 2
a = np.zeros(shape=(d+1, 2*d+1))
for i in range(0, 3):
    for j in range(0,5):
        a[i][j] = i*5 + j

In [2]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [3]:
# test mirror matrix generation
from fast_multipole_method import Vlm
b = Vlm(2)
b.V_matrix = a
c = b.get_mirror_matrix()
c.V_matrix

array([[14., 13., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [4]:
# test set & get
b.V_matrix

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [5]:
b.setlm(0, 0, 10)

In [6]:
b.getlm(0,0)

10.0

In [10]:
b.V_matrix

array([[ 0.,  1., 10.,  3.,  4.],
       [ 5.,  0.,  0.,  0.,  9.],
       [10.,  0.,  0.,  0., 14.]])

In [8]:
b.setlm_with_martix(1,-1,[[0,0,0],[0,0,0]])

In [9]:
b.getlm_matrix([1,2],[-1,1])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c.V_matrix = np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
c.V_matrix

In [ ]:
np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
T_degree

In [ ]:
T_order

In [ ]:
b.get_mirror_matrix().V_matrix