In [18]:
import numpy as np
d = 2
a = np.zeros(shape=(d+1, 2*d+1))
for i in range(0, 3):
    for j in range(0,5):
        a[i][j] = i*5 + j

In [19]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [3]:
# test mirror matrix generation
from fast_multipole_method import Vlm
b = Vlm(2)
b.V_matrix = a
c = b.get_mirror_matrix()
c.V_matrix

array([[14., 13., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [20]:
# test set & get
b.V_matrix = a

In [5]:
b.setlm(0, 0, 10)

In [6]:
b.getlm(0,0)

10.0

In [21]:
b.V_matrix

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [11]:
b.setlm_with_martix(0,-1,[[0,0,0],[0,0,0]])

In [9]:
b.getlm_matrix([1,2],[-1,1])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c.V_matrix = np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
c.V_matrix

In [ ]:
np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
T_degree

In [ ]:
T_order

In [ ]:
b.get_mirror_matrix().V_matrix