In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import numpy as np

In [2]:
from fmm_source import ggq_dist
from basic_operations import Vlm
from contracted_basis import CAO_basis, shell_pair

In [3]:
a = ggq_dist([0.4, 0.5, 0.3], 0.4, 1, [0, 1, 1])

In [4]:
mu = CAO_basis(np.array([0.5, 0.5, 0.5]), "C", 2, np.array([0, 0, 0]))

In [5]:
nu = CAO_basis(np.array([0.5, 0.5, 0.25]), "C", 2, np.array([0, 0, 0]))

In [6]:
sp = shell_pair(mu, nu)

In [7]:
sp.X_p

array([[[0.5       , 0.5       , 0.375     ],
        [0.5       , 0.5       , 0.45285976],
        [0.5       , 0.5       , 0.48243345]],

       [[0.5       , 0.5       , 0.29714024],
        [0.5       , 0.5       , 0.375     ],
        [0.5       , 0.5       , 0.43864636]],

       [[0.5       , 0.5       , 0.26756655],
        [0.5       , 0.5       , 0.31135364],
        [0.5       , 0.5       , 0.375     ]]])

In [8]:
sp.d

array([[ 0.00999345, -0.03993819, -0.0699886 ],
       [-0.03993819,  0.1596105 ,  0.27970511],
       [-0.0699886 ,  0.27970511,  0.49016167]])

In [9]:
sp.a_p

array([[5.8824988, 3.6247325, 3.1635393],
       [3.6247325, 1.3669662, 0.905773 ],
       [3.1635393, 0.905773 , 0.4445798]])

In [10]:
sp.a_k

array([[1.4706247 , 0.55460486, 0.20667043],
       [0.55460486, 0.34174155, 0.16773672],
       [0.20667043, 0.16773672, 0.11114495]])

In [11]:
sp.Mlm_init(3)

In [12]:
sp.Mlm[1][0].V_matrix

array([[0.       +0.j, 0.       +0.j, 0.       +0.j, 0.7793939+0.j,
        0.       +0.j, 0.       +0.j, 0.       +0.j],
       [0.       +0.j, 0.       +0.j, 0.       +0.j, 0.       +0.j,
        0.       +0.j, 0.       +0.j, 0.       +0.j],
       [0.       +0.j, 0.       +0.j, 0.       +0.j, 0.       +0.j,
        0.       +0.j, 0.       +0.j, 0.       +0.j],
       [0.       +0.j, 0.       +0.j, 0.       +0.j, 0.       +0.j,
        0.       +0.j, 0.       +0.j, 0.       +0.j]])

In [13]:
from fast_multipole_method import fmm_box
b = fmm_box(np.array([0.4, 0.4, 0.4]))

In [14]:

a = sp.M_expansion_to_box(b,3)

In [15]:
sp.X_p

array([[0.5       , 0.5       , 0.375     ],
       [0.5       , 0.5       , 0.45285976],
       [0.5       , 0.5       , 0.48243345],
       [0.5       , 0.5       , 0.29714024],
       [0.5       , 0.5       , 0.375     ],
       [0.5       , 0.5       , 0.43864636],
       [0.5       , 0.5       , 0.26756655],
       [0.5       , 0.5       , 0.31135364],
       [0.5       , 0.5       , 0.375     ]])

In [16]:
sp.Mlm

array([<basic_operations.Vlm object at 0x10f859908>,
       <basic_operations.Vlm object at 0x10f859780>], dtype=object)

In [17]:
a.V_matrix

array([[ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  3.87177431e+01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        -1.93588716e+00-1.93588716e+00j, -9.67943578e-01+0.00000000e+00j,
        -1.93588716e+00+1.93588716e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  5.92694502e-18+9.67943578e-02j,
         4.83971789e-02+4.83971789e-02j, -1.39595717e-01+0.00000000e+00j,
         4.83971789e-02-4.83971789e-02j,  5.92694502e-18-9.67943578e-02j,
         0.00000000e+00+0.00000000e+00j],
       [ 1.61323930e-03-1.61323930e-03j, -1.48173626e-19-2.41985895e-03j,
         2.14006797e-03+2.14006797e-03j,  3.69154784e-03+0.00000000e+00j,
         2.14006797e-03-2.14006797e-03j, -1.48173626e-19+2.4