In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import numpy as np

In [2]:
from fmm_source import ggq_dist
from basic_operations import Vlm

In [3]:
a = ggq_dist([0.4, 0.5, 0.3], 0.4, 1, [0, 1, 1])

In [4]:
from contracted_basis import CAO_basis

In [5]:
mu = CAO_basis(np.array([0.5, 0.5, 0.5]), "C", 2, np.array([1, 0, 0]))

In [6]:
nu = CAO_basis(np.array([0.5, 0.5, 0.5]), "C", 2, np.array([0, 1, 0]))

In [7]:
from contracted_basis import shell_pair

In [8]:
sp = shell_pair(mu, nu)

In [9]:
sp.X_p

array([[[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]],

       [[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]],

       [[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]]])

In [10]:
sp.d

array([[0.02430988, 0.09474778, 0.06111253],
       [0.09474778, 0.3692795 , 0.23818612],
       [0.06111253, 0.23818612, 0.1536306 ]])

In [11]:
sp.a_p

array([[5.8824988, 3.6247325, 3.1635393],
       [3.6247325, 1.3669662, 0.905773 ],
       [3.1635393, 0.905773 , 0.4445798]])

In [12]:
sp.a_k

array([[1.4706247 , 0.55460486, 0.20667043],
       [0.55460486, 0.34174155, 0.16773672],
       [0.20667043, 0.16773672, 0.11114495]])

In [13]:
sp.Mlm_init(3)

t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]
t: [0, 0]
t: [1, 0]
t: [1, 1]
u: [0, 0]
u: [1, 0]
v: [0, 0]


/Users/hang/Desktop/FMM/CFMM_for_DFT/CFMM_for_DFT/contracted_basis.py:75: RuntimeWarning: divide by zero encountered in power
  * binom(self.nu.pow[0], t-i) * np.power(X_p[0] - self.nu.x[0], self.nu.pow[0]-t+i)
/Users/hang/Desktop/FMM/CFMM_for_DFT/CFMM_for_DFT/contracted_basis.py:75: RuntimeWarning: invalid value encountered in double_scalars
  * binom(self.nu.pow[0], t-i) * np.power(X_p[0] - self.nu.x[0], self.nu.pow[0]-t+i)


In [14]:
sp.Mlm[0][0].V_matrix

array([[ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,
         0. +0.j],
       [ 0. +0.j,  0. +0.j,  0. +0.j, nan+nanj,  0. +0.j,  0. +0.j,
         0. +0.j],
       [ 0. +0.j, nan+nanj,  0. +0.j,  0. +0.j,  0. +0.j, nan+nanj,
         0. +0.j],
       [ 0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,  0. +0.j,
         0. +0.j]])

In [15]:
np.power(1, 0)

1