In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import fast_multipole_method
import numpy as np

In [2]:
d = 2
a = np.zeros(shape=(d+1, 2*d+1))
for i in range(0, 3):
    for j in range(0,5):
        a[i][j] = i*5 + j

In [3]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [4]:
# test mirror matrix generation
from fast_multipole_method import Vlm
b = Vlm(2)
b.V_matrix = a
c = b.get_mirror_matrix()
c.V_matrix

array([[14., 13., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [5]:
# test set & get
b.V_matrix = a

In [6]:
b.setlm(0, 0, 10)

In [7]:
b.getlm(0,0)

10.0

In [8]:
b.V_matrix

array([[ 0.,  1., 10.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [9]:
b.setlm_with_martix(0,-1,[[0,0,0],[0,0,0]])

AttributeError: 'Vlm' object has no attribute 'setlm_with_martix'

In [ ]:
b.getlm_matrix([1,2],[-1,1])

In [ ]:
c.V_matrix = np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
c.V_matrix

In [ ]:
np.dot(np.dot(T_degree, b.V_matrix), T_order)

In [ ]:
T_degree

In [ ]:
T_order

In [ ]:
b.get_mirror_matrix().V_matrix