In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from fast_multipole_method import operation as op
import numpy as np

In [2]:
x1 = [0.13, 0.17, 0.14]
r1 = op.cartesian_to_spherical(x1)
r1

array([0.25573424, 0.9914903 , 0.9179497 ])

In [3]:
op.spherical_to_cartesian(r1)

array([0.13, 0.17, 0.14])

In [4]:
x2 = np.array([0.87, 0.83, 0.92])
op.distance_cal(x1, x2)

1.2615863030328127

In [5]:
r2 = op.cartesian_to_spherical(x2)
r2

array([1.51400132, 0.91768381, 0.76187309])

In [6]:
P1 = op.AL_polynoimal(2, np.float(np.cos(r1[1])))
P1

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.54744332, -0.83684276,  0.        ],
       [-0.05045872, -1.37437194,  2.10091743]], dtype=float128)

In [7]:
P1

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.54744332, -0.83684276,  0.        ],
       [-0.05045872, -1.37437194,  2.10091743]], dtype=float128)

In [8]:
np.cos(r1[1])

0.5474433209040426